---
email: "{{ vault_email }}"

app_path: /srv/conductor
frontend_path: "{{ app_path }}/frontend"

client_domain: "www.{{ root_domain }}"
client_root: "{{ frontend_path }}"

venv_path: /srv/virtualenv
ssh_private_key: "{{ vault_ssh_private_key }}"
django_env:
  CONDUCTOR_EMAIL: "{{ email }}"
  CORS_ORIGIN_WHITELIST: "{{ client_domain }}"
  DJANGO_ALLOWED_HOSTS: ".{{ root_domain }}"
  DJANGO_SETTINGS_MODULE: "{{ django_settings_module }}"
  MAILGUN_API_KEY: "{{ mailgun.api_key }}"
  RABBITMQ_USER: "{{ rabbitmq.user }}"
  RABBITMQ_PASSWORD: "{{ rabbitmq.password }}"
  RABBITMQ_VHOST: "{{ rabbitmq.vhost }}"
  ROLLBAR_ENABLED: "true"
  ROLLBAR_ACCESS_TOKEN: "{{ rollbar.access_token }}"
  ROLLBAR_ENVIRONMENT: "{{ deployment }}"
  SECRET_KEY: "{{ vault_secret_key }}"
  POSTGRES_DB: "{{ postgres.db }}"
  POSTGRES_USER: "{{ postgres.user }}"
  POSTGRES_PASSWORD: "{{ postgres.password }}"
  STATIC_ROOT: /var/www/api/
  STATIC_URL: /static/
  STRIPE_API_KEY: "{{ stripe.api_key }}"
  STRIPE_PUBLISHABLE_KEY: "{{ stripe.publishable_key }}"

postgres:
  db: conductor
  user: conductor
  password: "{{ vault_postgres_password }}"
  storage_path: /var/lib/postgresql/9.5/main

wale:
  s3_prefix: "s3://collegeconductor/pgbackups/{{ deployment }}"

rabbitmq:
  vhost: conductor
  user: "{{ vault.rabbitmq.user }}"
  password: "{{ vault.rabbitmq.password }}"

cert_dir: "/etc/letsencrypt/live/{{ root_domain }}-0001"

aws:
  access_key_id: "{{ vault.aws.access_key_id }}"
  secret_access_key: "{{ vault.aws.secret_access_key }}"
  region: "{{ vault.aws.region }}"

datadog:
  api_key: "{{ vault_datadog_api_key }}"

mailgun:
  api_key: "{{ vault_mailgun_api_key }}"

rollbar:
  access_token: "{{ vault_rollbar_access_token }}"
  post_client_item_access_token: "{{ vault.rollbar.post_client_item_access_token }}"

segment:
  write_key: "{{ vault_segment_write_key }}"
