---
app_path: /srv/conductor
frontend_path: "{{ app_path }}/frontend"

client_domain: "www.{{ root_domain }}"
client_root: "{{ frontend_path }}"

venv_path: /srv/virtualenv
ssh_private_key: "{{ vault_ssh_private_key }}"
django_env:
  DJANGO_SETTINGS_MODULE: "{{ django_settings_module }}"

static_root: /var/www/conductor/
static_url: /static/

postgres:
  db: "{{ secrets.postgres.db }}"
  user: "{{ secrets.postgres.user }}"
  password: "{{ secrets.postgres.password }}"
  storage_path: /var/lib/postgresql/9.5/main

wale:
  s3_prefix: "s3://collegeconductor/pgbackups/{{ deployment }}"

cert_dir: "/etc/letsencrypt/live/{{ root_domain }}-0001"

aws:
  access_key_id: "{{ vault.aws.access_key_id }}"
  secret_access_key: "{{ vault.aws.secret_access_key }}"
  region: "{{ vault.aws.region }}"

datadog:
  api_key: "{{ vault_datadog_api_key }}"

segment:
  write_key: "{{ vault_segment_write_key }}"
