---
- hosts: webservers
  roles:
    - role: kamaln7.swapfile
      swapfile_size: 1GB
      become: yes
    - role: nodesource.node
      become: yes
    - role: Datadog.datadog
      datadog_api_key: "{{ datadog.api_key }}"
      when: deployment == "production"
    - web
